In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf
from sklearn import metrics
import warnings
import pickle
import math
import joblib

warnings.filterwarnings("ignore")


ModuleNotFoundError: No module named 'tensorflow'

In [2]:
data = pd.read_csv("diabetes.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Diabetes_binary       253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

In [3]:
catcol = ['HighBP', 'CholCheck','BMI',
       'Smoker', 'Stroke', 'PhysActivity','NoDocbcCost', 'Sex','Age', 'Education']

new_df = data[catcol]
new_df.head()

HighBP  CholCheck   BMI  Smoker  Stroke  PhysActivity  NoDocbcCost  Sex  \
0     1.0        1.0  40.0     1.0     0.0           0.0          0.0  0.0   
1     0.0        0.0  25.0     1.0     0.0           1.0          1.0  0.0   
2     1.0        1.0  28.0     0.0     0.0           0.0          1.0  0.0   
3     1.0        1.0  27.0     0.0     0.0           1.0          0.0  0.0   
4     1.0        1.0  24.0     0.0     0.0           1.0          0.0  0.0   

    Age  Education  
0   9.0        4.0  
1   7.0        6.0  
2   9.0        4.0  
3  11.0        3.0  
4  11.0        5.0

In [4]:
new_df.describe()

HighBP      CholCheck            BMI         Smoker  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        0.429001       0.962670      28.382364       0.443169   
std         0.494934       0.189571       6.608694       0.496761   
min         0.000000       0.000000      12.000000       0.000000   
25%         0.000000       1.000000      24.000000       0.000000   
50%         0.000000       1.000000      27.000000       0.000000   
75%         1.000000       1.000000      31.000000       1.000000   
max         1.000000       1.000000      98.000000       1.000000   

              Stroke   PhysActivity    NoDocbcCost            Sex  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        0.040571       0.756544       0.084177       0.440342   
std         0.197294       0.429169       0.277654       0.496429   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       1.000000       0.000000       0.000000   
50%         0.000000       1.000000       0.000000       0.000000   
75%         0.000000       1.000000       0.000000       1.000000   
max         1.000000       1.000000       1.000000       1.000000   

                 Age      Education  
count  253680.000000  253680.000000  
mean        8.032119       5.050434  
std         3.054220       0.985774  
min         1.000000       1.000000  
25%         6.000000       4.000000  
50%         8.000000       5.000000  
75%        10.000000       6.000000  
max        13.000000       6.000000

In [5]:
y = data['Diabetes_binary'].values
X = new_df.values

In [6]:
y =y.astype('int')
X =X.astype('int')

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, test_size=0.25,shuffle=True)
print(y_train)
print(X_train)
print(y_test)
print(X_test)

[0 0 0 ... 0 0 0]
[[ 0  1 20 ...  1 12  4]
 [ 0  1 27 ...  1 12  6]
 [ 0  1 23 ...  0  4  5]
 ...
 [ 1  1 25 ...  1 13  4]
 [ 1  1 32 ...  1  6  3]
 [ 0  1 28 ...  0  6  6]]
[0 0 0 ... 0 0 1]
[[ 1  1 30 ...  1  6  5]
 [ 1  1 33 ...  0  5  6]
 [ 0  0 19 ...  1  2  5]
 ...
 [ 0  1 22 ...  0  3  6]
 [ 1  1 42 ...  0  8  5]
 [ 1  1 39 ...  1  7  4]]


In [8]:
scaler = StandardScaler()


X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
print(X_train)

[[ 0  1 20 ...  1 12  4]
 [ 0  1 27 ...  1 12  6]
 [ 0  1 23 ...  0  4  5]
 ...
 [ 1  1 25 ...  1 13  4]
 [ 1  1 32 ...  1  6  3]
 [ 0  1 28 ...  0  6  6]]


In [ ]:
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 30
hidden_nodes_layer4 = 30
hidden_nodes_layer5 = 30

nn = tf.keras.models.Sequential()

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")) 

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))

nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer5, activation="relu"))

nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

nn.summary()

In [ ]:
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
fit_model = nn.fit(X_train, y_train,epochs=10)

In [ ]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")