In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, average_precision_score, balanced_accuracy_score
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score, precision_recall_fscore_support 
#from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import warnings
import pickle
import math
import joblib

warnings.filterwarnings("ignore")


In [2]:
data = pd.read_csv("diabetes.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Diabetes_binary       253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

In [3]:
catcol = ['HighBP', 'CholCheck', 'Smoker', 'Stroke', 'PhysActivity', 'NoDocbcCost', 'Sex', 'BMI', 'Age', 'Education']

new_df = data[catcol]
new_df.head()

HighBP  CholCheck  Smoker  Stroke  PhysActivity  NoDocbcCost  Sex   BMI  \
0     1.0        1.0     1.0     0.0           0.0          0.0  0.0  40.0   
1     0.0        0.0     1.0     0.0           1.0          1.0  0.0  25.0   
2     1.0        1.0     0.0     0.0           0.0          1.0  0.0  28.0   
3     1.0        1.0     0.0     0.0           1.0          0.0  0.0  27.0   
4     1.0        1.0     0.0     0.0           1.0          0.0  0.0  24.0   

    Age  Education  
0   9.0        4.0  
1   7.0        6.0  
2   9.0        4.0  
3  11.0        3.0  
4  11.0        5.0

In [4]:
new_df.describe()

HighBP      CholCheck         Smoker         Stroke  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        0.429001       0.962670       0.443169       0.040571   
std         0.494934       0.189571       0.496761       0.197294   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       1.000000       0.000000       0.000000   
50%         0.000000       1.000000       0.000000       0.000000   
75%         1.000000       1.000000       1.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

        PhysActivity    NoDocbcCost            Sex            BMI  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        0.756544       0.084177       0.440342      28.382364   
std         0.429169       0.277654       0.496429       6.608694   
min         0.000000       0.000000       0.000000      12.000000   
25%         1.000000       0.000000       0.000000      24.000000   
50%         1.000000       0.000000       0.000000      27.000000   
75%         1.000000       0.000000       1.000000      31.000000   
max         1.000000       1.000000       1.000000      98.000000   

                 Age      Education  
count  253680.000000  253680.000000  
mean        8.032119       5.050434  
std         3.054220       0.985774  
min         1.000000       1.000000  
25%         6.000000       4.000000  
50%         8.000000       5.000000  
75%        10.000000       6.000000  
max        13.000000       6.000000

In [30]:
y = data['Diabetes_binary'].values
X = new_df.values

In [6]:
#y = np.asarray(y)
#X = np.asarray(X)
y =y.astype('int')
X =X.astype('int')

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, test_size=0.25,stratify=y)
print(y_train)
print(X_train)
print(y_test)
print(X_test)

[0 0 0 ... 0 1 0]
[[ 1  1  1 ... 28 12  6]
 [ 0  1  0 ... 23  8  6]
 [ 0  1  1 ... 27  1  5]
 ...
 [ 1  1  0 ... 25 12  5]
 [ 1  1  1 ... 36  9  4]
 [ 0  1  0 ... 58  8  4]]
[0 1 0 ... 0 0 0]
[[ 1  1  0 ... 28  3  6]
 [ 1  1  0 ... 41  9  6]
 [ 1  1  0 ... 26  7  5]
 ...
 [ 0  1  0 ... 21  8  6]
 [ 1  1  0 ... 25 10  5]
 [ 0  1  1 ... 26  8  4]]


In [8]:
print(y_train.shape)
print(X_train.shape)
print(y_test.shape)
print(X_test.shape)

(190260,)
(190260, 10)
(63420,)
(63420, 10)


In [9]:
scaler = StandardScaler()


X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [10]:
log_reg = LogisticRegression(solver='lbfgs',max_iter=200, random_state=1)


In [11]:
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [12]:
intercept = log_reg.intercept_
coefficient = log_reg.coef_

In [13]:
new_list = [intercept, coefficient]

In [14]:
print(new_list)
print(len(intercept))
print(len(coefficient))

[array([-6.39263736]), array([[ 1.05536815,  1.3802279 ,  0.10296261,  0.54287255, -0.28914229,
         0.33932448,  0.21510698,  0.07135242,  0.15535998, -0.17540396]])]
1
1


In [15]:
accuracy = log_reg.score(X_test, y_test)
print("accuracy = ", accuracy * 100, "%")

accuracy =  86.01387574897508 %


In [16]:
#d_pred = log_reg.predict_proba(X_test)
#print(d_pred)
d_pred = log_reg.predict(X_test)
print(d_pred)

[0 0 0 ... 0 0 0]


In [17]:
len(d_pred)

63420

In [18]:
sum(d_pred)

1153

In [19]:
balanced_accuracy_score(y_test,d_pred)
#dataset not balanced 

0.5262528667178048

In [20]:
confusion_matrix(y_test,d_pred)

array([[53990,   593],
       [ 8277,   560]])

In [21]:
precision_recall_fscore_support(y_test,d_pred)

(array([0.86707245, 0.48568951]),
 array([0.98913581, 0.06336992]),
 array([0.92409071, 0.11211211]),
 array([54583,  8837]))

In [22]:
joblib.dump(log_reg, open('model.pkl', 'wb'))

In [23]:
model = joblib.load(open('model.pkl', 'rb'))

In [24]:
joblib.dump(X_scaler, open('Xscaler.pkl', 'wb'))

In [25]:
Xscaler = joblib.load(open('Xscaler.pkl', 'rb'))

In [26]:
#X_test[0]

In [27]:
my_list = [[1, 1, 1, 1, 1, 1, 1, 20, 10, 5]]
my_list_sample = X_scaler.transform(np.asarray(my_list))
print(len(my_list_sample), my_list_sample)


1 [[ 1.15338805  0.19718781  1.12075113  4.86426252  0.5673396   3.29737758
   1.12661812 -1.26671943  0.64514494 -0.05204723]]


In [28]:
diabetesPredict = model.predict(my_list_sample)
diabetesProbability = model.predict_proba(my_list_sample)
print('prediction:', diabetesPredict)
print('Probability:', diabetesProbability[0][0])

prediction: [0]
Probability: 0.7172773481750667


In [29]:
log_reg.coef_


array([[ 1.05536815,  1.3802279 ,  0.10296261,  0.54287255, -0.28914229,
         0.33932448,  0.21510698,  0.07135242,  0.15535998, -0.17540396]])