In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, average_precision_score, balanced_accuracy_score
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score, precision_recall_fscore_support 
#from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import warnings
import pickle
import math
import joblib

warnings.filterwarnings("ignore")


In [2]:
data = pd.read_csv("diabetes.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Diabetes_binary       253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

In [3]:
catcol = ['HighBP', 'CholCheck', 'Smoker', 'Stroke', 'PhysActivity', 'NoDocbcCost', 'Sex', 'BMI', 'Age', 'Education']

new_df = data[catcol]
new_df.head()

HighBP  CholCheck  Smoker  Stroke  PhysActivity  NoDocbcCost  Sex   BMI  \
0     1.0        1.0     1.0     0.0           0.0          0.0  0.0  40.0   
1     0.0        0.0     1.0     0.0           1.0          1.0  0.0  25.0   
2     1.0        1.0     0.0     0.0           0.0          1.0  0.0  28.0   
3     1.0        1.0     0.0     0.0           1.0          0.0  0.0  27.0   
4     1.0        1.0     0.0     0.0           1.0          0.0  0.0  24.0   

    Age  Education  
0   9.0        4.0  
1   7.0        6.0  
2   9.0        4.0  
3  11.0        3.0  
4  11.0        5.0

In [4]:
new_df.describe()

HighBP      CholCheck         Smoker         Stroke  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        0.429001       0.962670       0.443169       0.040571   
std         0.494934       0.189571       0.496761       0.197294   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       1.000000       0.000000       0.000000   
50%         0.000000       1.000000       0.000000       0.000000   
75%         1.000000       1.000000       1.000000       0.000000   
max         1.000000       1.000000       1.000000       1.000000   

        PhysActivity    NoDocbcCost            Sex            BMI  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        0.756544       0.084177       0.440342      28.382364   
std         0.429169       0.277654       0.496429       6.608694   
min         0.000000       0.000000       0.000000      12.000000   
25%         1.000000       0.000000       0.000000      24.000000   
50%         1.000000       0.000000       0.000000      27.000000   
75%         1.000000       0.000000       1.000000      31.000000   
max         1.000000       1.000000       1.000000      98.000000   

                 Age      Education  
count  253680.000000  253680.000000  
mean        8.032119       5.050434  
std         3.054220       0.985774  
min         1.000000       1.000000  
25%         6.000000       4.000000  
50%         8.000000       5.000000  
75%        10.000000       6.000000  
max        13.000000       6.000000

In [6]:
y = data['Diabetes_binary'].values
X = new_df.values

In [7]:
#y = np.asarray(y)
#X = np.asarray(X)
y =y.astype('int')
X =X.astype('int')

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, test_size=0.25, shuffle=True)
print(y_train)
print(X_train)
print(y_test)
print(X_test)

[0 0 0 ... 0 0 0]
[[ 0  1  1 ... 20 12  4]
 [ 0  1  0 ... 27 12  6]
 [ 0  1  0 ... 23  4  5]
 ...
 [ 1  1  1 ... 25 13  4]
 [ 1  1  1 ... 32  6  3]
 [ 0  1  1 ... 28  6  6]]
[0 0 0 ... 0 0 1]
[[ 1  1  0 ... 30  6  5]
 [ 1  1  0 ... 33  5  6]
 [ 0  0  1 ... 19  2  5]
 ...
 [ 0  1  0 ... 22  3  6]
 [ 1  1  0 ... 42  8  5]
 [ 1  1  1 ... 39  7  4]]


In [9]:
print(y_train.shape)
print(X_train.shape)
print(y_test.shape)
print(X_test.shape)

(190260,)
(190260, 10)
(63420,)
(63420, 10)


In [10]:
scaler = StandardScaler()


X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [20]:
log_reg = LogisticRegression(solver='lbfgs',max_iter=600, random_state=78)


In [21]:
log_reg.fit(X_train, y_train)

LogisticRegression(max_iter=600, random_state=78)

In [22]:
intercept = log_reg.intercept_
coefficient = log_reg.coef_

In [23]:
new_list = [intercept, coefficient]

In [24]:
print(new_list)
print(len(intercept))
print(len(coefficient))

[array([-6.43164625]), array([[ 1.04602974,  1.39628918,  0.09822076,  0.52325788, -0.29354257,
         0.35236967,  0.21398552,  0.07212122,  0.15671175, -0.17670364]])]
1
1


In [25]:
accuracy = log_reg.score(X_test, y_test)
print("accuracy = ", accuracy * 100, "%")

accuracy =  85.92872910753705 %


In [26]:
#d_pred = f_log_reg.predict_proba(X_test)
#print(d_pred)
d_pred = log_reg.predict(X_test)
print(d_pred)

[0 0 0 ... 0 0 0]


In [27]:
len(d_pred)

63420

In [28]:
sum(d_pred)

1126

In [29]:
confusion_matrix(y_test,d_pred)

array([[53934,   564],
       [ 8360,   562]])

In [30]:
precision_recall_fscore_support(y_test,d_pred)

(array([0.86579767, 0.4991119 ]),
 array([0.989651  , 0.06299036]),
 array([0.92359066, 0.11186306]),
 array([54498,  8922]))

In [41]:
joblib.dump(log_reg, open('model.pkl', 'wb'))

In [42]:
model = joblib.load(open('model.pkl', 'rb'))

In [43]:
joblib.dump(X_scaler, open('Xscaler.pkl', 'wb'))

In [44]:
Xscaler = joblib.load(open('Xscaler.pkl', 'rb'))

In [45]:
X_test[0]

array([ 1,  1,  0,  0,  1,  0,  1, 30,  6,  5])

In [46]:
my_list = [[1, 1, 1, 1, 1, 1, 1, 20, 10, 5]]
my_list_sample = X_scaler.transform(np.asarray(my_list))
print(len(my_list_sample), my_list_sample)


1 [[ 1.15307878  0.19702954  1.11859344  4.81695211  0.56750148  3.29065519
   1.12521379 -1.26730075  0.64328106 -0.04986598]]


In [38]:
diabetesPredict = log_reg.predict(my_list_sample)
diabetesProbability = log_reg.predict_proba(my_list_sample)
print('prediction:', diabetesPredict)
print('Probability:', diabetesProbability[0][0])

prediction: [0]
Probability: 0.7442280861926671


In [39]:
log_reg.coef_


array([[ 1.04602974,  1.39628918,  0.09822076,  0.52325788, -0.29354257,
         0.35236967,  0.21398552,  0.07212122,  0.15671175, -0.17670364]])

In [40]:
print("Classification Report is:\n",classification_report(y_test,d_pred))

Classification Report is:
               precision    recall  f1-score   support

           0       0.87      0.99      0.92     54498
           1       0.50      0.06      0.11      8922

    accuracy                           0.86     63420
   macro avg       0.68      0.53      0.52     63420
weighted avg       0.81      0.86      0.81     63420



In [47]:
import matplotlib.pyplot as plt
import hvplot.pandas
import plotly.express as px
import seaborn as sns

In [48]:
import seaborn as sns

In [ ]:
# plt.figure(figsize=(10,10))
# g=sns.heatmap(final_df.corr(),annot=True,cmap ='BuPu')
# g