In [20]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, average_precision_score, balanced_accuracy_score
from sklearn.metrics import f1_score, precision_score, recall_score, accuracy_score, precision_recall_fscore_support 
#from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import warnings
import pickle
import math
import joblib

warnings.filterwarnings("ignore")


In [21]:
data = pd.read_csv("diabetes.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Diabetes_binary       253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

In [22]:
catcol = ['HighBP', 'CholCheck','BMI',
       'Smoker', 'Stroke', 'PhysActivity','NoDocbcCost', 'Sex','Age', 'Education']

new_df = data[catcol]
new_df.head()

HighBP  CholCheck   BMI  Smoker  Stroke  PhysActivity  NoDocbcCost  Sex  \
0     1.0        1.0  40.0     1.0     0.0           0.0          0.0  0.0   
1     0.0        0.0  25.0     1.0     0.0           1.0          1.0  0.0   
2     1.0        1.0  28.0     0.0     0.0           0.0          1.0  0.0   
3     1.0        1.0  27.0     0.0     0.0           1.0          0.0  0.0   
4     1.0        1.0  24.0     0.0     0.0           1.0          0.0  0.0   

    Age  Education  
0   9.0        4.0  
1   7.0        6.0  
2   9.0        4.0  
3  11.0        3.0  
4  11.0        5.0

In [23]:
new_df.describe()

HighBP      CholCheck            BMI         Smoker  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        0.429001       0.962670      28.382364       0.443169   
std         0.494934       0.189571       6.608694       0.496761   
min         0.000000       0.000000      12.000000       0.000000   
25%         0.000000       1.000000      24.000000       0.000000   
50%         0.000000       1.000000      27.000000       0.000000   
75%         1.000000       1.000000      31.000000       1.000000   
max         1.000000       1.000000      98.000000       1.000000   

              Stroke   PhysActivity    NoDocbcCost            Sex  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        0.040571       0.756544       0.084177       0.440342   
std         0.197294       0.429169       0.277654       0.496429   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       1.000000       0.000000       0.000000   
50%         0.000000       1.000000       0.000000       0.000000   
75%         0.000000       1.000000       0.000000       1.000000   
max         1.000000       1.000000       1.000000       1.000000   

                 Age      Education  
count  253680.000000  253680.000000  
mean        8.032119       5.050434  
std         3.054220       0.985774  
min         1.000000       1.000000  
25%         6.000000       4.000000  
50%         8.000000       5.000000  
75%        10.000000       6.000000  
max        13.000000       6.000000

In [24]:
y = data['Diabetes_binary'].values
X = new_df.values


In [25]:
#y = np.asarray(y)
#X = np.asarray(X)
y =y.astype('int')
X =X.astype('int')

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, test_size=0.25,shuffle=True)
print(y_train)
print(X_train)
print(y_test)
print(X_test)

[0 0 0 ... 0 0 0]
[[ 0  1 20 ...  1 12  4]
 [ 0  1 27 ...  1 12  6]
 [ 0  1 23 ...  0  4  5]
 ...
 [ 1  1 25 ...  1 13  4]
 [ 1  1 32 ...  1  6  3]
 [ 0  1 28 ...  0  6  6]]
[0 0 0 ... 0 0 1]
[[ 1  1 30 ...  1  6  5]
 [ 1  1 33 ...  0  5  6]
 [ 0  0 19 ...  1  2  5]
 ...
 [ 0  1 22 ...  0  3  6]
 [ 1  1 42 ...  0  8  5]
 [ 1  1 39 ...  1  7  4]]


In [27]:
print(y_train.shape)
print(X_train.shape)
print(y_test.shape)
print(X_test.shape)

(190260,)
(190260, 10)
(63420,)
(63420, 10)


In [28]:
scaler = StandardScaler()


X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [29]:
log_reg = LogisticRegression()


In [30]:
log_reg.fit(X_train, y_train)

LogisticRegression()

In [31]:
intercept = log_reg.intercept_
coefficient = log_reg.coef_

In [32]:
new_list = [intercept, coefficient]

In [33]:
print(new_list)
print(len(intercept))
print(len(coefficient))

[array([-6.40367853]), array([[ 1.0820621 ,  1.02322733,  0.07475983,  0.11134669,  0.36103886,
        -0.26408663,  0.49151216,  0.248182  ,  0.16721628, -0.15754561]])]
1
1


In [34]:
accuracy = log_reg.score(X_test, y_test)
print("accuracy = ", accuracy * 100, "%")

accuracy =  85.90034689372438 %


In [35]:
#d_pred = log_reg.predict_proba(X_test)
#print(d_pred)
d_pred = log_reg.predict(X_test)
print(d_pred)

[0 0 0 ... 0 0 0]


In [36]:
len(d_pred)

63420

In [37]:
sum(d_pred)

1144

In [38]:
balanced_accuracy_score(y_test,d_pred)
#dataset not balanced 

0.5261555349612356

In [39]:
confusion_matrix(y_test,d_pred)

array([[53916,   582],
       [ 8360,   562]])

In [40]:
precision_recall_fscore_support(y_test,d_pred)

(array([0.86575888, 0.49125874]),
 array([0.98932071, 0.06299036]),
 array([0.92342473, 0.11166302]),
 array([54498,  8922]))

In [41]:
joblib.dump(log_reg, open('model.pkl', 'wb'))

In [42]:
model = joblib.load(open('model.pkl', 'rb'))

In [43]:
X_test[0]

array([ 1,  1, 30,  0,  0,  1,  0,  1,  6,  5])

In [44]:
my_list = [[1, 1, 75, 1, 1, 0, 1, 1, 6, 2]]
my_list_sample = X_scaler.transform(np.asarray(my_list))
print(len(my_list_sample), my_list_sample)


1 [[ 1.15307878  0.19702954  7.0543078   1.11859344  4.81695211 -1.76210996
   3.29065519  1.12521379 -0.66696058 -3.09430962]]


In [45]:
diabetesPredict = log_reg.predict(my_list_sample)
diabetesProbability = log_reg.predict_proba(my_list_sample)
print('prediction:', diabetesPredict)
print('Probability:', diabetesProbability)

prediction: [1]
Probability: [[0.4564505 0.5435495]]


In [46]:
log_reg.coef_


array([[ 1.0820621 ,  1.02322733,  0.07475983,  0.11134669,  0.36103886,
        -0.26408663,  0.49151216,  0.248182  ,  0.16721628, -0.15754561]])